<?php
  date_default_timezone_set('UTC');
  require_once('for_zad2/xml_saver.php');
  require_once('common/common.php');
  require_once('for_zad2/file_io.php');
  require_once('for_zad2/api/forecast_api.php');
  require_once('for_zad2/api/weather_api.php');
  require_once('for_zad2/api/api_helper.php');
  require_once('for_zad2/view_helper.php');
?>